---
title: "AFL Player Stats"
author: "Timothy Davies"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(fitzRoy)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)
```

```{r fetch-data, eval=TRUE, cache=TRUE}
season_fryzigg <- fetch_player_stats(season = 2021, source = "fryzigg")
```

```{r home-away-finals}
season_home_away <- season_fryzigg %>%
  filter(between(match_round, 1, 23))
```


```{r player-totals-fryzigg}
player_totals_fryzigg <- season_fryzigg %>% 
  mutate(player_name = paste(player_first_name, player_last_name)) %>% 
  group_by(player_name, player_team, guernsey_number, player_height_cm, player_weight_kg) %>% 
  summarise(games = n(),
            kicks = sum(kicks),
            marks = sum(marks),
            handballs = sum(handballs),
            disposals = sum(disposals),
            kick_handball_ratio = kicks/handballs,
            effective_disposals = sum(effective_disposals),
            disposal_efficiency_percentage = sum(disposal_efficiency_percentage),
            goals = sum(goals),
            behinds = sum(behinds),
            hitouts = sum(hitouts),
            tackles = sum(tackles),
            rebounds = sum(rebounds),
            inside_fifties = sum(inside_fifties),
            clearances = sum(clearances),
            clangers = sum(clangers),
            free_kicks_for = sum(free_kicks_for),
            free_kicks_against = sum(free_kicks_against),
            brownlow_votes = sum(brownlow_votes),
            contested_possessions = sum(contested_possessions),
            uncontested_possessions = sum(uncontested_possessions),
            contested_marks = sum(contested_marks),
            marks_inside_fifty = sum(marks_inside_fifty),
            one_percenters = sum(one_percenters),
            bounces = sum(bounces),
            goal_assists = sum(goal_assists),
            time_on_ground_percentage = sum(time_on_ground_percentage),
            afl_fantasy_score = sum(afl_fantasy_score),
            supercoach_score = sum(supercoach_score),
            centre_clearances = sum(centre_clearances),
            stoppage_clearances = sum(stoppage_clearances),
            score_involvements = sum(score_involvements),
            metres_gained = sum(metres_gained),
            turnovers = sum(turnovers),
            intercepts = sum(intercepts),
            tackles_inside_fifty = sum(tackles_inside_fifty),
            contest_def_losses = sum(contest_def_losses),
            contest_def_one_on_ones = sum(contest_def_one_on_ones),
            contest_def_winrate = ((contest_def_one_on_ones - contest_def_losses)/contest_def_one_on_ones)*100,
            contest_off_one_on_ones = sum(contest_off_one_on_ones),
            contest_off_wins = sum(contest_off_wins),
            contest_off_winrate = (contest_off_wins/contest_off_one_on_ones)*100,
            def_half_pressure_acts = sum(def_half_pressure_acts),
            effective_kicks = sum(effective_kicks),
            f50_ground_ball_gets = sum(f50_ground_ball_gets),
            ground_ball_gets = sum(ground_ball_gets),
            hitouts_to_advantage = sum(hitouts_to_advantage),
            marks_on_lead = sum(marks_on_lead),
            pressure_acts = sum(pressure_acts),
            rating_points = sum(rating_points),
            ruck_contests = sum(ruck_contests),
            score_launches = sum(score_launches),
            shots_at_goal = sum(shots_at_goal),
            spoils = sum(spoils))
```

```{r player-averages-fryzigg}
player_avg_fryzigg <- season_fryzigg %>% 
  mutate(player_name = paste(player_first_name, player_last_name)) %>% 
  group_by(player_name, player_team, guernsey_number, player_height_cm, player_weight_kg) %>% 
  summarise(games = n(),
            kicks = mean(kicks),
            marks = mean(marks),
            handballs = mean(handballs),
            disposals = mean(disposals),
            kick_handball_ratio = kicks/handballs,
            effective_disposals = mean(effective_disposals),
            disposal_efficiency_percentage = mean(disposal_efficiency_percentage),
            goals = mean(goals),
            behinds = mean(behinds),
            hitouts = mean(hitouts),
            tackles = mean(tackles),
            rebounds = mean(rebounds),
            inside_fifties = mean(inside_fifties),
            clearances = mean(clearances),
            clangers = mean(clangers),
            free_kicks_for = mean(free_kicks_for),
            free_kicks_against = mean(free_kicks_against),
            brownlow_votes = mean(brownlow_votes),
            contested_possessions = mean(contested_possessions),
            uncontested_possessions = mean(uncontested_possessions),
            contested_marks = mean(contested_marks),
            marks_inside_fifty = mean(marks_inside_fifty),
            one_percenters = mean(one_percenters),
            bounces = mean(bounces),
            goal_assists = mean(goal_assists),
            time_on_ground_percentage = mean(time_on_ground_percentage),
            afl_fantasy_score = mean(afl_fantasy_score),
            supercoach_score = mean(supercoach_score),
            centre_clearances = mean(centre_clearances),
            stoppage_clearances = mean(stoppage_clearances),
            score_involvements = mean(score_involvements),
            metres_gained = mean(metres_gained),
            turnovers = mean(turnovers),
            intercepts = mean(intercepts),
            tackles_inside_fifty = mean(tackles_inside_fifty),
            contest_def_losses = mean(contest_def_losses),
            contest_def_one_on_ones = mean(contest_def_one_on_ones),
            contest_def_winrate = ((contest_def_one_on_ones - contest_def_losses)/contest_def_one_on_ones)*100,
            contest_off_one_on_ones = mean(contest_off_one_on_ones),
            contest_off_wins = mean(contest_off_wins),
            contest_off_winrate = (contest_off_wins/contest_off_one_on_ones)*100,
            def_half_pressure_acts = mean(def_half_pressure_acts),
            effective_kicks = mean(effective_kicks),
            f50_ground_ball_gets = mean(f50_ground_ball_gets),
            ground_ball_gets = mean(ground_ball_gets),
            hitouts_to_advantage = mean(hitouts_to_advantage),
            marks_on_lead = mean(marks_on_lead),
            pressure_acts = mean(pressure_acts),
            rating_points = mean(rating_points),
            ruck_contests = mean(ruck_contests),
            score_launches = mean(score_launches),
            shots_at_goal = mean(shots_at_goal),
            spoils = mean(spoils))
```

# For Josh

```{r cp-mg, include=TRUE}
player_cp_mg <- player_avg_fryzigg %>% 
  select(player_name, player_team, games, contested_possessions, metres_gained)

fig_cp_mg <- plot_ly(
  data = player_cp_mg, x = ~contested_possessions, y = ~metres_gained,
  text = ~paste("Team:", player_team, "<br>Player:", player_name, "<br>CP:", round(contested_possessions, 1), "<br>MG:", round(metres_gained, 1)),
  hover_info = text
)
fig_cp_mg <- fig_cp_mg %>% 
  layout(title = 'Metres Gained vs. Contested Possessions (Average)',
         xaxis = list(title = 'Average CP'),
         yaxis = list(title = 'Average MG'))
fig_cp_mg
```